# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink: /:categories/:year/:month/:day/:title 
permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: redcarpet
highlights: pygments
lsi: false
timezone: Asia/Shanghai
safe: false
theme: minima
JB :
  ASSET_PATH : http://zhu8.qiniudn.com/assets
  IMAGE_PATH : http://zhu8.qiniudn.com/images
# auto: true # deprecated

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
url: http://huangxianxia.github.io
title: huangxianxia(人生记)
tagline: On The Way to understand world
about: <a href="http://huangxianxia.github.io/"><strong>黄贤夏</strong></a>huangxianxia(nick)的个人网站，浙江人士，85年生人，嵌入式软件一枚，欢迎<strong>Fork</strong>本站@<a href="https://huangxianxia.github.io/fork">Github</a>。
author:
  name: huangxianxia(nick)
  email: nick.huangxianxia@gmail.com 
  github: huangxianxia
  twitter: nick_huang85
  facebook: 
  googleplus: 
  feedburner : 
